version: '3'
services:
  pdfconverter2:
    image: pdfconverter2:latest
    volumes:
      - pages_data:/pages
      - /leech:/leech   # Keep this as it is for /leech
   # command: your_command_here

  embedder:
    image: embedder:latest
    volumes:
      - pages_data:/pages
   # command: your_command_here

volumes:
  pages_data:
