
services:
#  postgres:
#    image: postgres:14
#    container_name: postgres
#    environment:
#      POSTGRES_USER: postgres 
#      POSTGRES_PASSWORD: postgres 
#      POSTGRES_DB: postgres 
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#
  web-frontend:
    build:
      context: .
      dockerfile: ./app/Dockerfile   

    container_name: web-frontend
    environment:
      POSTGRES_HOST: 172.20.0.5
      POSTGRES_DB: postgres 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      LLM_API_URL: http://llm_container:5000/generate
#    depends_on:
#      - postgres
#      - llm
    ports:
      - "5000:5000"

#  llm:
#    image: your_llm_image  # Replace with your LLM Docker image
#    container_name: llm_container
#    ports:
#      - "5001:5000"
#
#volumes:
#  postgres_data:
#
